# Generated by Django 6.1 on 2026-09-01 00:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. 2026/2027 SUG General Elections', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('SUG', 'Student Union Government (SUG) General Election'), ('FACULTY', 'Faculty Representative Election'), ('DEPARTMENTAL', 'Departmental Association Election')], default='SUG', max_length=30)),
                ('faculty', models.CharField(blank=True, help_text='Required if Faculty Election', max_length=150, null=True)),
                ('department', models.CharField(blank=True, help_text='Required if Departmental Election', max_length=150, null=True)),
                ('target_level', models.IntegerField(blank=True, help_text='Optional level restriction (e.g. 400)', null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft (Setup Stage)'), ('ACTIVE', 'Active (Voting Open)'), ('PAUSED', 'Paused (Temporary Hold)'), ('CONCLUDED', 'Concluded (Official Results Finalized)')], default='DRAFT', max_length=20)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_elections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. President, Vice President, Secretary General', max_length=150)),
                ('order_num', models.IntegerField(default=1, help_text='Display order on ballot')),
                ('max_choices', models.IntegerField(default=1, help_text='Maximum candidate choices allowed')),
                ('description', models.TextField(blank=True)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='elections.election')),
            ],
            options={
                'ordering': ['election', 'order_num', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('nickname', models.CharField(blank=True, help_text='Campaign Alias / Moniker', max_length=100, null=True)),
                ('matric_no', models.CharField(blank=True, max_length=50, null=True)),
                ('photo_url', models.CharField(blank=True, default='/static/img/default_avatar.svg', max_length=300, null=True)),
                ('manifesto', models.TextField(help_text='Key campaign agenda and vision')),
                ('cgpa_cleared', models.BooleanField(default=True, help_text='Academic clearance by Senate Committee')),
                ('status', models.CharField(choices=[('APPROVED', 'Cleared & Approved'), ('PENDING', 'Pending Screening'), ('DISQUALIFIED', 'Disqualified')], default='APPROVED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidacies', to=settings.AUTH_USER_MODEL)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='elections.position')),
            ],
            options={
                'ordering': ['position', 'full_name'],
            },
        ),
        migrations.CreateModel(
            name='Ballot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('receipt_token', models.CharField(db_index=True, help_text='Zero-knowledge receipt token for public verifier', max_length=64)),
                ('prev_ballot_hash', models.CharField(db_index=True, max_length=64)),
                ('ballot_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('nonce', models.CharField(default='065cfb08b5f84886a67157e2a5c145a3', max_length=32)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ballots', to='elections.candidate')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ballots', to='elections.election')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ballots', to='elections.position')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='HasVoted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('receipt_token', models.CharField(help_text='Receipt token issued to voter', max_length=64, unique=True)),
                ('polling_terminal_ip', models.CharField(default='127.0.0.1', max_length=45)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elections.election')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Voter Participation Record',
                'verbose_name_plural': 'Voter Participation Records (HasVoted)',
                'unique_together': {('election', 'voter')},
            },
        ),
    ]
