# Generated by Django 6.1 on 2026-09-10 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ballot',
            name='nonce',
            field=models.CharField(default='895fc3a19a8e4ec9bee6cbeb861345ec', max_length=32),
        ),
    ]
