# Generated by Django 6.1 on 2026-09-01 00:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FingerprintTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finger_index', models.CharField(choices=[('RIGHT_THUMB', 'Right Thumb'), ('RIGHT_INDEX', 'Right Index Finger'), ('LEFT_THUMB', 'Left Thumb'), ('LEFT_INDEX', 'Left Index Finger')], default='RIGHT_INDEX', max_length=30)),
                ('encrypted_template', models.TextField(help_text='AES-256 GCM ciphertext of minutiae features (Base64)')),
                ('nonce', models.CharField(help_text='GCM 96-bit nonce (Base64)', max_length=64)),
                ('tag', models.CharField(help_text='GCM 128-bit authentication tag (Base64)', max_length=64)),
                ('minutiae_count', models.IntegerField(default=0)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fingerprint_template', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fingerprint Template',
                'verbose_name_plural': 'Fingerprint Templates (Encrypted at Rest)',
            },
        ),
    ]
