# Generated by Django 6.1 on 2026-09-07 00:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biometrics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WebAuthnCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credential_id', models.TextField(help_text='Base64URL-encoded credential ID from the authenticator', unique=True)),
                ('public_key', models.TextField(help_text='Base64URL-encoded COSE public key bytes')),
                ('sign_count', models.PositiveIntegerField(default=0, help_text='Signature counter for replay attack detection')),
                ('device_name', models.CharField(default='Personal Device', help_text='Friendly name for the enrolled device (e.g. Samsung Galaxy, iPhone)', max_length=200)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webauthn_credentials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'WebAuthn Credential',
                'verbose_name_plural': 'WebAuthn Credentials (FIDO2 Device Keys)',
            },
        ),
    ]
