# Generated by Django 6.1 on 2026-09-01 00:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('event_type', models.CharField(choices=[('SYSTEM_INIT', 'System Initialized / Genesis Block'), ('LOGIN_STEP1_SUCCESS', 'Step 1: Password Authenticated'), ('LOGIN_STEP1_FAIL', 'Step 1: Password Failed'), ('LOGIN_STEP2_SUCCESS', 'Step 2: OTP Authenticated'), ('LOGIN_STEP2_FAIL', 'Step 2: OTP Failed'), ('BIOMETRIC_MATCH_SUCCESS', 'Step 3: Biometric Minutiae Matched'), ('BIOMETRIC_MATCH_FAIL', 'Step 3: Biometric Minutiae Rejected'), ('BIOMETRIC_ENROLL', 'Biometric Template Enrolled'), ('BALLOT_CAST', 'Ballot Cast & Cryptographically Sealed'), ('DOUBLE_VOTE_BLOCKED', 'Double-Vote Attempt Blocked'), ('STAGE_SKIP_BLOCKED', 'Authentication Stage-Skipping Blocked'), ('ADMIN_ACTION', 'Electoral Commission Administrative Action'), ('SECURITY_LOCKOUT', 'Account Locked (Exceeded Retries)')], db_index=True, max_length=50)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('matric_no', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('ip_address', models.CharField(default='127.0.0.1', max_length=45)),
                ('details', models.TextField(blank=True, help_text='JSON payload of event details')),
                ('prev_hash', models.CharField(db_index=True, max_length=64)),
                ('current_hash', models.CharField(db_index=True, max_length=64, unique=True)),
            ],
            options={
                'verbose_name': 'Audit Log Entry',
                'verbose_name_plural': 'Audit Log Entries (Hash-Chained)',
                'ordering': ['id'],
            },
        ),
    ]
