# Generated by Django 6.1 on 2026-09-07 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='event_type',
            field=models.CharField(choices=[('SYSTEM_INIT', 'System Initialized / Genesis Block'), ('LOGIN_STEP1_SUCCESS', 'Step 1: Password Authenticated'), ('LOGIN_STEP1_FAIL', 'Step 1: Password Failed'), ('LOGIN_STEP2_SUCCESS', 'Step 2: OTP Authenticated'), ('LOGIN_STEP2_FAIL', 'Step 2: OTP Failed'), ('BIOMETRIC_MATCH_SUCCESS', 'Step 3: Biometric Verified'), ('BIOMETRIC_MATCH_FAIL', 'Step 3: Biometric Rejected'), ('BIOMETRIC_ENROLL', 'Biometric Template Enrolled'), ('BALLOT_CAST', 'Ballot Cast & Cryptographically Sealed'), ('DOUBLE_VOTE_BLOCKED', 'Double-Vote Attempt Blocked'), ('STAGE_SKIP_BLOCKED', 'Authentication Stage-Skipping Blocked'), ('ADMIN_ACTION', 'Electoral Commission Administrative Action'), ('SECURITY_LOCKOUT', 'Account Locked (Exceeded Retries)'), ('WEBAUTHN_REGISTER', 'WebAuthn Device Fingerprint Enrolled'), ('WEBAUTHN_AUTH_SUCCESS', 'Step 3: Device Fingerprint Verified'), ('WEBAUTHN_AUTH_FAIL', 'Step 3: Device Fingerprint Rejected')], db_index=True, max_length=50),
        ),
    ]
